name: Compile LaTeX

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Compile LaTeX 
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: ./
        root_file: main.tex

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
        
    - name: Upload PDF file
      if: steps.compile_latex.outputs.built == 'true' 
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: joaquin-soro-cv.pdf  
      env:
        TEXINPUTS: ".:.///:"
